const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Plugins.AJAX,
		C3.Plugins.Camera3D,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.gamepad,
		C3.Plugins.Json,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.NinePatch,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Behaviors.EightDir,
		C3.Behaviors.Physics,
		C3.Behaviors.LOS,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.solid,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.solid.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.EightDir.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetMeshPoint,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layertolayerx,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Exps.layertolayery,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.gamepad.Exps.Axis,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Audio.Acts.PlayAtPositionByName,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.ScriptsInEvents["Futilities🧰_Event8_Act1"],
		C3.Plugins.System.Exps.log10,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Exps.stringsub,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Exps.cpuutilisation,
		C3.Plugins.System.Exps.gpuutilisation,
		C3.Plugins.System.Exps.objectcount,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Physics.Exps.Mass,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.TemplateName,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Physics.Acts.ApplyImpulseToward,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Plugins.Audio.Acts.SetListenerObject,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Exps.MaxSpeed,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Behaviors.LOS.Cnds.HasLOSToPosition,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Camera3D.Acts.SetFieldOfView,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Exps.LookX,
		C3.Plugins.Camera3D.Exps.LookY,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Text.Cnds.PickChildren,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.ScriptsInEvents["Moptions💾_Event9_Act3"],
		C3.ScriptsInEvents["Moptions💾_Event10_Act1"],
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Exps.TagAtPosition,
		C3.ScriptsInEvents["Moptions💾_Event16_Act2"],
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Exps.lowercase,
		C3.ScriptsInEvents["Moptions💾_Event19_Act1"],
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Exps.Text
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Timer: 0},
	{GlobalTimer: 0},
	{AJAX: 0},
	{"3DCamera": 0},
	{Audio: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Gamepad: 0},
	{JSON_Options: 0},
	{JSON_OptionsDefault: 0},
	{role: 0},
	{UI_Text: 0},
	{UI_OptionsBackground: 0},
	{UI_OptionsTextSF: 0},
	{UI_TextSF: 0},
	{Sine: 0},
	{Sine2: 0},
	{UI_Logo: 0},
	{UI_HUD_Background: 0},
	{UI_Icons: 0},
	{SineAngle: 0},
	{SineHorizontal: 0},
	{SineVertical: 0},
	{UI_Title: 0},
	{initX: 0},
	{initY: 0},
	{Tween: 0},
	{UI_Box: 0},
	{initWidth: 0},
	{UI_Rectangle: 0},
	{bbEnemy1: 0},
	{bbEnemy2: 0},
	{SineZElevation: 0},
	{bbPickup: 0},
	{bbPlayer: 0},
	{bbPlayerWeapon: 0},
	{bbDecor: 0},
	{bbWall_Permanent: 0},
	{bbWall_Level0: 0},
	{bbWall_Level1: 0},
	{bbWall_Level2: 0},
	{bbWall_Level3: 0},
	{IN_Move_D_Up: 0},
	{IN_Move_D_Down: 0},
	{IN_Move_D_Left: 0},
	{IN_Move_D_Right: 0},
	{IN_Move_A_Active: 0},
	{IN_Move_A_Angle: 0},
	{IN_Aim_A_Angle: 0},
	{IN_Shoot: 0},
	{isDead: 0},
	{health: 0},
	{aimAngle: 0},
	{damageMultiplier: 0},
	{rateOfFireMultiplier: 0},
	{weaponLevel: 0},
	{R_Base_RateOfFire: 0},
	{R_Base_Health: 0},
	{R_Base_Damage: 0},
	{Player: 0},
	{R_distanceFromPlayer_Y: 0},
	{R_distanceFromPlayer_Z: 0},
	{isStopped: 0},
	{CameraHelper: 0},
	{Ground: 0},
	{AimHelper: 0},
	{R_knockbackForce: 0},
	{R_knockbackTime: 0},
	{damage: 0},
	{isDestroyed: 0},
	{PlayerProjectile: 0},
	{hitCount: 0},
	{Wall: 0},
	{R_MaxHealth: 0},
	{R_MovementSpeed: 0},
	{R_Damage: 0},
	{R_AttackCooldown: 0},
	{R_ChargeTime: 0},
	{R_JumpImpulse: 0},
	{R_JumpTime: 0},
	{initMass: 0},
	{knockbackForce: 0},
	{knockbackAngle: 0},
	{knockbackTime: 0},
	{isChasingPlayer: 0},
	{targetX: 0},
	{targetY: 0},
	{hasEntered: 0},
	{Enemy: 0},
	{Spawner: 0},
	{R_Value: 0},
	{R_BoostTime: 0},
	{R_BoostMultiplier: 0},
	{isPickedUp: 0},
	{Pickup: 0},
	{Rotate: 0},
	{Exit: 0},
	{ExitDecor: 0},
	{ExitDecor2: 0},
	{ExitHelper: 0},
	{EnemyProjectile: 0},
	{EnemyHitbox: 0},
	{PlayerHitbox: 0},
	{"8Direction": 0},
	{Physics: 0},
	{LineOfSight: 0},
	{BoundToLayout: 0},
	{Player_: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Projectile_: 0},
	{Enemy_: 0},
	{BillboardSprites: 0},
	{Pickup_: 0},
	{EnemyBillboard: 0},
	{Solid: 0},
	{Wall_: 0},
	{BillboardTBs: 0},
	{scaleMultiplier: 0},
	{soundName: 0},
	{variantCount: 0},
	{x: 0},
	{y: 0},
	{decorSpawnCells: 0},
	{decorCellWidth: 0},
	{decorCellHeight: 0},
	{decorCellPadding: 0},
	{layerName: 0},
	{oldValue: 0},
	{oldRangeMin: 0},
	{oldRangeMax: 0},
	{newRangeMin: 0},
	{newRangeMax: 0},
	{name: 0},
	{percent: 0},
	{from: 0},
	{to: 0},
	{decay: 0},
	{C_HexDigits: 0},
	{hex: 0},
	{x1: 0},
	{y1: 0},
	{z1: 0},
	{x2: 0},
	{y2: 0},
	{z2: 0},
	{hours: 0},
	{minutes: 0},
	{seconds: 0},
	{divider: 0},
	{cameraFOV_target: 0},
	{cameraFOV: 0},
	{hasPlayerSpawned: 0},
	{totalTime: 0},
	{roundTimeBonus: 0},
	{roundTimeLeft: 0},
	{isBetweenRounds: 0},
	{useMouseInput: 0},
	{isPaused: 0},
	{NOTHING: 0},
	{NO: 0},
	{YES: 0},
	{ANIM_Idle: 0},
	{ANIM_Walking: 0},
	{ANIM_Hit: 0},
	{ANIM_Shooting: 0},
	{ANIM_Death: 0},
	{ANIM_Charge: 0},
	{ANIM_Jump: 0},
	{AUDIO_SFX: 0},
	{AUDIO_BGM: 0},
	{FRAME_SpawnProjectile: 0},
	{DIR_Up: 0},
	{DIR_Down: 0},
	{DIR_Left: 0},
	{DIR_Right: 0},
	{ET_V1: 0},
	{ET_V2: 0},
	{LAYER_Main: 0},
	{LAYER_UI: 0},
	{PT_Time: 0},
	{PT_Damage: 0},
	{PT_RateOfFire: 0},
	{PT_Health: 0},
	{ROLE_DevInfo: 0},
	{ROLE_Health: 0},
	{ROLE_Damage: 0},
	{ROLE_RateOfFire: 0},
	{ROLE_Time: 0},
	{ROLE_Notification: 0},
	{ROLE_BoostDamage: 0},
	{ROLE_BoostRateOfFire: 0},
	{TIMER_AttackCooldown: 0},
	{TIMER_Destroy: 0},
	{TIMER_Invincible: 0},
	{TIMER_Knockback: 0},
	{TIMER_Idle: 0},
	{TIMER_TargetLost: 0},
	{TIMER_BoostDamage: 0},
	{TIMER_BoostRateOfFire: 0},
	{TIMER_EverySecond: 0},
	{TIMER_PlayerRewindZDelay: 0},
	{TIMER_Charge: 0},
	{TIMER_Jump: 0},
	{TIMER_StartRound: 0},
	{TWEEN_ZElevation_Up: 0},
	{TWEEN_ZElevation_Down: 0},
	{TWEEN_Position: 0},
	{TWEEN_ColorOverdrive: 0},
	{TWEEN_Y_HideUpgradeOptions: 0},
	{TWEEN_Width: 0},
	{UT_Damage: 0},
	{UT_RateOfFire: 0},
	{UT_Health: 0},
	{WT_Permanent: 0},
	{WT_Level: 0},
	{W_X: 0},
	{W_Y: 0},
	{W_Player: 0},
	{W_Pickup: 0},
	{W_bbWall: 0},
	{W_Exit: 0},
	{ANIM_Spawning: 0},
	{EFFECTS_Effect1: 0},
	{OT_ObjectType1: 0},
	{SIGNAL_Signal1: 0},
	{TEMPLATE_Template1: 0},
	{C_Level_Round_Time_Default: 0},
	{C_Level_Decoration_MaxAmount: 0},
	{C_Level_Decoration_SpawnChance: 0},
	{C_Player_AimHelper_Distance: 0},
	{C_Player_Projectile_ZElevation: 0},
	{C_Player_Hit_Invincibility_Time: 0},
	{C_Player_Weapon_Distance: 0},
	{C_Player_Rewind_Speed: 0},
	{C_Player_Base_Damage_Increase: 0},
	{C_Player_Base_RateOfFire_Increase: 0},
	{C_Player_Base_Health_Increase: 0},
	{C_Player_Aim_Random: 0},
	{C_Camera_FOV_Step: 0},
	{C_Camera_FOV_Min: 0},
	{C_Camera_FOV_Max: 0},
	{C_Enemy_Chase_Timeout: 0},
	{C_Enemy_Idle_Time_Min: 0},
	{C_Enemy_Idle_Time_Max: 0},
	{C_Enemy_Projectile_ZElevation: 0},
	{C_Projectile_Lifetime: 0},
	{C_Projectile_DamageBoost_ScaleMultiplier: 0},
	{C_ARRAY_ProjectileLevels: 0},
	{C_Wall_Destructible_HitCount: 0},
	{C_Audio_SFX_DebounceTime: 0},
	{C_UI_UpgradeBox_OffsetY: 0},
	{C_UI_BBCode_Outline: 0},
	{C_Tween_ColorOverdrive: 0},
	{value: 0},
	{isMoving: 0},
	{movementAngle: 0},
	{upgradeType: 0},
	{z: 0},
	{lookX: 0},
	{lookY: 0},
	{lookZ: 0},
	{text: 0},
	{C_StorageKeyPrefix: 0},
	{LAYER_Options: 0},
	{SIG_OptionsLoaded: 0},
	{SIG_OptionsChanged: 0},
	{ROLE_Labels: 0},
	{ROLE_Controls: 0},
	{ROLE_Groups: 0},
	{W_DEFAULT_: 0},
	{W_DOWN_: 0},
	{W_LABEL_: 0},
	{W_MAX_: 0},
	{W_MIN_: 0},
	{W_STEP_: 0},
	{W_TOGGLE_: 0},
	{W_UP_: 0},
	{variable: 0},
	{padding: 0},
	{valueMax: 0},
	{isFirstRun: 0},
	{valueStep: 0},
	{valueMin: 0},
	{tag: 0},
	{group: 0},
	{label: 0},
	{control: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	GlobalTimer: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	_3DCamera: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	JSON_Options: class extends self.IJSONInstance {},
	JSON_OptionsDefault: class extends self.IJSONInstance {},
	UI_Text: class extends self.ITextInstance {},
	UI_OptionsBackground: class extends self.ITiledBackgroundInstance {},
	UI_OptionsTextSF: class extends self.ISpriteFontInstance {},
	UI_TextSF: class extends self.ISpriteFontInstance {},
	UI_Logo: class extends self.ISpriteInstance {},
	UI_HUD_Background: class extends self.ISpriteInstance {},
	UI_Icons: class extends self.ISpriteInstance {},
	UI_Title: class extends self.ITextInstance {},
	UI_Box: class extends self.IWorldInstance {},
	UI_Rectangle: class extends self.ITiledBackgroundInstance {},
	bbEnemy1: class extends self.ISpriteInstance {},
	bbEnemy2: class extends self.ISpriteInstance {},
	bbPickup: class extends self.ISpriteInstance {},
	bbPlayer: class extends self.ISpriteInstance {},
	bbPlayerWeapon: class extends self.ISpriteInstance {},
	bbDecor: class extends self.ISpriteInstance {},
	bbWall_Permanent: class extends self.ITiledBackgroundInstance {},
	bbWall_Level0: class extends self.ITiledBackgroundInstance {},
	bbWall_Level1: class extends self.ITiledBackgroundInstance {},
	bbWall_Level2: class extends self.ITiledBackgroundInstance {},
	bbWall_Level3: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	CameraHelper: class extends self.ISpriteInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	AimHelper: class extends self.ISpriteInstance {},
	PlayerProjectile: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Spawner: class extends self.ISpriteInstance {},
	Pickup: class extends self.ISpriteInstance {},
	Exit: class extends self.ISpriteInstance {},
	ExitDecor: class extends self.ISpriteInstance {},
	ExitDecor2: class extends self.ISpriteInstance {},
	ExitHelper: class extends self.ISpriteInstance {},
	EnemyProjectile: class extends self.ISpriteInstance {},
	EnemyHitbox: class extends self.ISpriteInstance {},
	PlayerHitbox: class extends self.ISpriteInstance {},
	Player_: class extends self.ISpriteInstance {},
	Projectile_: class extends self.ISpriteInstance {},
	Enemy_: class extends self.ISpriteInstance {},
	BillboardSprites: class extends self.ISpriteInstance {},
	Pickup_: class extends self.ISpriteInstance {},
	EnemyBillboard: class extends self.ISpriteInstance {},
	Wall_: class extends self.ISpriteInstance {},
	BillboardTBs: class extends self.ITiledBackgroundInstance {}
}