const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Json,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Exps.roundtodp,
		C3.Plugins.Audio.Exps.PlaybackTime,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.Arr.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Exps.Front,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.ScriptsInEvents["Futilities🧰_Event8_Act1"],
		C3.Plugins.System.Exps.log10,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Exps.stringsub,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.System.Exps.cpuutilisation,
		C3.Plugins.System.Exps.gpuutilisation,
		C3.Plugins.System.Exps.objectcount,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Json.Acts.AddTo,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Exps.Text
	];
};
self.C3_JsPropNameTable = [
	{Browser: 0},
	{Timer: 0},
	{GlobalTimer: 0},
	{Audio: 0},
	{Keyboard: 0},
	{Touch: 0},
	{BlockSpawner: 0},
	{Selection: 0},
	{isPlaying: 0},
	{Notes: 0},
	{role: 0},
	{UI_Text: 0},
	{initWidth: 0},
	{UI_Rectangle: 0},
	{fallCount: 0},
	{fallDelay: 0},
	{column: 0},
	{row: 0},
	{isSelected: 0},
	{instrumentNumber: 0},
	{Block: 0},
	{Collider: 0},
	{Container: 0},
	{Symbol: 0},
	{Backgorund: 0},
	{"9patch": 0},
	{Tween: 0},
	{Block_: 0},
	{Symbol_: 0},
	{value: 0},
	{layerName: 0},
	{oldValue: 0},
	{oldRangeMin: 0},
	{oldRangeMax: 0},
	{newRangeMin: 0},
	{newRangeMax: 0},
	{name: 0},
	{percent: 0},
	{from: 0},
	{to: 0},
	{decay: 0},
	{C_HexDigits: 0},
	{hex: 0},
	{x1: 0},
	{y1: 0},
	{z1: 0},
	{x2: 0},
	{y2: 0},
	{z2: 0},
	{hours: 0},
	{minutes: 0},
	{seconds: 0},
	{divider: 0},
	{blockWidth: 0},
	{blockHeight: 0},
	{selectionMatchByColour: 0},
	{selectionMatchBySymbol: 0},
	{isMusicEnabled: 0},
	{musicBPM: 0},
	{musicBPMMultiplier: 0},
	{beat: 0},
	{beatPos: 0},
	{nextBeatPos: 0},
	{volumeDb_SFX: 0},
	{volumeDb_BGM: 0},
	{C_Health_Max: 0},
	{health: 0},
	{selectionToHealthMultiplier: 0},
	{isGameOver: 0},
	{NOTHING: 0},
	{NO: 0},
	{YES: 0},
	{ANIM_Unselected: 0},
	{ANIM_Selected: 0},
	{ANIM_Whole: 0},
	{ANIM_Halves: 0},
	{ANIM_Triplet: 0},
	{ANIM_Quarters: 0},
	{ANIM_WholeLong: 0},
	{ANIM_Circle: 0},
	{ANIM_Diamond: 0},
	{ANIM_Pentagon: 0},
	{ANIM_Square: 0},
	{ANIM_Cross: 0},
	{AUDIO_BGM: 0},
	{AUDIO_SFX: 0},
	{COLOR_Red: 0},
	{COLOR_Yellow: 0},
	{COLOR_Green: 0},
	{COLOR_Blue: 0},
	{COLOR_Cyan: 0},
	{LAYER_Main: 0},
	{ROLE_DevInfo: 0},
	{TWEEN_Y_Fall: 0},
	{TWEEN_Y_Rise: 0},
	{W_X: 0},
	{W_Y: 0},
	{W_Note: 0},
	{LAYER_GameOver: 0},
	{TIMER_RestartTimeout: 0},
	{DIR_Up: 0},
	{DIR_Down: 0},
	{DIR_Left: 0},
	{DIR_Right: 0},
	{EFFECTS_Effect1: 0},
	{OT_ObjectType1: 0},
	{SIGNAL_Signal1: 0},
	{TEMPLATE_Template1: 0},
	{C_Block_DistancePadding: 0},
	{C_Block_Selection_Min: 0},
	{C_Block_Selection_Max: 0},
	{C_Block_Row_Display_Offset: 0},
	{C_Block_Fall_Delay_Min: 0},
	{C_Block_Fall_Delay_Max: 0},
	{C_Block_Fall_Time_Offset: 0},
	{C_Block_Fall_CountToTime_Multiplier: 0},
	{C_Beat_Resolution: 0},
	{C_Block_Rise_Y: 0},
	{isMatch: 0},
	{fallDelays_CSV: 0},
	{columns: 0},
	{rows: 0},
	{blockUID: 0},
	{colour: 0},
	{symbol: 0}
];

self.InstanceType = {
	Browser: class extends self.IInstance {},
	GlobalTimer: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	BlockSpawner: class extends self.IJSONInstance {},
	Selection: class extends self.IArrayInstance {},
	Notes: class extends self.IArrayInstance {},
	UI_Text: class extends self.ITextInstance {},
	UI_Rectangle: class extends self.ITiledBackgroundInstance {},
	Block: class extends self.ISpriteInstance {},
	Collider: class extends self.ITiledBackgroundInstance {},
	Container: class extends self.ITiledBackgroundInstance {},
	Symbol: class extends self.ISpriteInstance {},
	Backgorund: class extends self.ITiledBackgroundInstance {},
	_9patch: class extends self.IWorldInstance {},
	Block_: class extends self.ISpriteInstance {},
	Symbol_: class extends self.ISpriteInstance {}
}